notifications: 
  email: 
  - michaelc@email.gwu.edu
  - lwrubel@email.gwu.edu
branches: 
  only: 
  - master
install: pip install -r requirements.txt
language: python
python: 
- "2.7"
before_install: 
- sed "s/cx_Oracle/#cx_Oracle/g" requirements.txt > test.txt
- mv test.txt requirements.txt
script: 
- cp lp/lp/local_settings.py.template lp/lp/local_settings.py
- python lp/manage.py migrate
- python lp/manage.py test lp
dist: trusty
os: linux
env: 
  matrix: 
  - DJANGO_VERSION=1.8

  
